# Generated by Django 2.1.4 on 2020-03-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.IntegerField(primary_key=True, serialize=False)),
                ('numberClient', models.CharField(max_length=10)),
                ('nameClient', models.CharField(max_length=50)),
                ('lastNameClient', models.CharField(max_length=50)),
                ('cityClient', models.CharField(max_length=50)),
                ('addressClient', models.CharField(max_length=80)),
                ('telephoneClient', models.CharField(max_length=10)),
                ('emailClient', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'ordering': ['nameClient'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('idInvoice', models.IntegerField(primary_key=True, serialize=False)),
                ('dateInvoice', models.DateField()),
                ('TotalPriceInvoice', models.FloatField()),
                ('nameClientInvoice', models.CharField(max_length=50)),
                ('lastNameClientInvoice', models.CharField(max_length=50)),
                ('productsInvoice', models.CharField(max_length=50)),
                ('nameProductsInvoice', models.CharField(max_length=50)),
                ('employeeInvoice', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.IntegerField(primary_key=True, serialize=False)),
                ('nameProduct', models.CharField(max_length=50)),
                ('priceSaleProduct', models.FloatField()),
                ('quantityProduct', models.IntegerField()),
                ('categoryProduct', models.CharField(max_length=50)),
                ('descriptionProduct', models.CharField(max_length=300)),
                ('nameSupplierProduct', models.CharField(max_length=50)),
                ('entryDateProduct', models.DateField()),
                ('expirationDateProduct', models.DateField(blank=True, null=True)),
                ('pricePurchaseProduct', models.FloatField()),
                ('utilityProduct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('idSupplier', models.IntegerField(primary_key=True, serialize=False)),
                ('nitSupplier', models.CharField(max_length=20)),
                ('nameSupplier', models.CharField(max_length=50)),
                ('categorySupplier', models.CharField(max_length=50)),
                ('telephoneSupplier', models.CharField(max_length=10)),
                ('emailSupplier', models.CharField(max_length=80, null=True)),
                ('citySupplier', models.CharField(max_length=50)),
                ('addressSupplier', models.CharField(max_length=80)),
                ('descriptionSupplier', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Supplier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(to='ecommerce.Product'),
        ),
    ]
